name: Run Python Script

on:
  push:
    branches:
      - main  # Specify the branch you want to monitor
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Check Chrome Version
      run: google-chrome --version  # This will output the installed Chrome version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python Test.py  # Ensure this path is correct

    - name: Upload downloaded file
      uses: actions/upload-artifact@v3
      with:
        name: downloaded-file
        path: '*.xlsx'  # Keep the pattern quoted
